### PR TITLE
Update home.html

### PR DESCRIPTION
**Pull request by cwpeng**
Add text.

### CODE REVIEW

**Comment by chiachil** [comment]
ok

**Comment by KaoTuz** [comment]
** Panda 是否會滾下來**

-----------------

與這支Panda有關聯的選項:

[https://media3.giphy.com/media/HDR31jsQUPqQo/giphy.gif](url)

提交 PR 前，請先檢查以下是否已完成：

* [ ] Panda 前翻
* [ ] Panda 後翻
* [ ] Panda 側翻

-----------------

補充說明:

搖搖木馬Panda

**Review by SsuJ-Chang — CHANGES_REQUESTED** [review]
我覺得不行

**Review by ChengTze-Wu — CHANGES_REQUESTED** [review]
Failed, please give up

**Review by HDsee — COMMENTED** [review]
美賽

**Review by magam54 — CHANGES_REQUESTED** [review]
No

**Review by TWcamel — CHANGES_REQUESTED** [review]
Not really good, please check again

**Review by HsinI65018 — COMMENTED** [review]
do it again

**Review by henry5720 — COMMENTED** [review]
gg

**Review by gandolfreddy — CHANGES_REQUESTED** [review]
Doesn't meet requirement.

**Review by kristychaotw — CHANGES_REQUESTED** [review]
nono

**Review by TWcamel — APPROVED** [review]
perfect code, gooooooooooooooooooooooooood!!

**Comment by HsinI65018** [comment]
Good

**Comment by cwpeng** [comment]
Done.

**Review by wc-su — APPROVED** [review]
ok

**Review by SsuJ-Chang — APPROVED** [review]
好～啦～

**Comment by chiachil** [comment]
good

**Review by gandolfreddy — APPROVED** [review]
great

**Review by magam54 — APPROVED** [review]
ok

**Review by ChengTze-Wu — APPROVED** [review]
🤬

**Review by kristychaotw — COMMENTED** [review]
Well done!

**Review by HsinI65018 — COMMENTED** [review]
Good

**Pull request merged**
